### ISSUE TITLE
wrong root folder /image/root/janus/lib/janus/loggers after build

### ISSUE THREAD

**Issue by 4563453** [bartbalaz/janus-container#12]
Hello, I ran your script and get this error in docker logs. how to fix this?

CONFIG_GEN_SCRIPT=

Failed to load /janus/etc/janus/janus.jcfg, trying the INI instead...
Error reading/parsing the configuration file in /janus/etc/janus, going on with the defaults and the command line arguments
[ERR] [config.c:janus_config_parse:205] Error parsing config file at line 181: syntax error
[ERR] [config.c:janus_config_parse:191]   -- Error reading configuration file 'janus.cfg'... error 2 (No such file or directory)
Logger plugins folder: /image/root/janus/lib/janus/loggers
[WARN]  Couldn't access logger plugins folder...

**Comment by 4563453** [comment]
I see 
RUN_WITH_HOST_CONFIGURATION_DIR=
CONFIG_GEN_SCRIPT=
could be the reason why the root path still in build path for image

**Comment by bartbalaz** [comment]
I need to know a bit more about what are you trying to achieve. Basically you have several options for where the Janus configuration may come from:
- Embedded into the build image, then upon the target image creation it may be built into the target image and used from there
- Or you may specify a configuration folder that will be mounted by the target image
-- This image may either contain a static classic Janus GW configuration files 
-- Or it may contain a configuration generation script that, based on some environment values (it's up to you which ones) passed to the image, it will generate the Janus GW configuration files. I did not provide any examples of such script but that would be simple JSON "generator" 

If you haven't figured this yet, please send me all the commands and parameter values that you have used to build the image and then to run the image. That will help me figure out this issue.

**Comment by 4563453** [comment]
I try to build and run the container using your scripts. I get a janus application with has a persistent  /image/root/ in its path variable build in. 
I am not able to remove this. "/image/root/" looks like an prefix for path variable in the container with confiugration.

**Comment by bartbalaz** [comment]
Sorry but I really don't understand what you are doing. To answer your question I need:
- Full list of parameters you have set
- Full log of the commands you have typed and printouts

**Comment by 4563453** [comment]
janus is working now.
